// Industries that support "emergency" and "24 hour" keyword modifiers
export const emergencyIndustries = [
  'plumber',
  'electrician',
  'hvac',
  'locksmith',
  'auto-repair',
  'roofer',
  'veterinarian',
  'cleaning-service',
  'tow-truck',
  'pest-control',
]

export const industryPresets = [
  {
    id: 'plumber',
    label: 'Plumber',
    services: [
      'plumbing repair',
      'drain cleaning',
      'water heater',
      'pipe repair',
      'sewer line',
      'leak detection',
      'faucet installation',
      'toilet repair',
      'garbage disposal',
      'emergency plumbing',
    ],
  },
  {
    id: 'dentist',
    label: 'Dentist',
    services: [
      'dental cleaning',
      'teeth whitening',
      'dental implants',
      'root canal',
      'crown',
      'filling',
      'emergency dentist',
      'cosmetic dentistry',
      'orthodontics',
      'pediatric dentist',
    ],
  },
  {
    id: 'restaurant',
    label: 'Restaurant',
    services: [
      'restaurant',
      'dining',
      'takeout',
      'delivery',
      'catering',
      'brunch',
      'dinner',
      'happy hour',
      'private dining',
      'food',
    ],
  },
  {
    id: 'electrician',
    label: 'Electrician',
    services: [
      'electrical repair',
      'wiring',
      'panel upgrade',
      'outlet installation',
      'ceiling fan',
      'lighting',
      'generator',
      'EV charger',
      'electrical inspection',
    ],
  },
  {
    id: 'hvac',
    label: 'HVAC',
    services: [
      'AC repair',
      'heating repair',
      'furnace',
      'air conditioning',
      'HVAC maintenance',
      'duct cleaning',
      'thermostat',
      'heat pump',
      'AC installation',
    ],
  },
  {
    id: 'salon',
    label: 'Salon / Barber',
    services: [
      'haircut',
      'hair color',
      'highlights',
      'blowout',
      "men's haircut",
      'balayage',
      'keratin treatment',
      'hair extensions',
      'beard trim',
    ],
  },
  {
    id: 'lawyer',
    label: 'Lawyer',
    services: [
      'attorney',
      'lawyer',
      'legal services',
      'consultation',
      'personal injury',
      'family law',
      'criminal defense',
      'estate planning',
      'bankruptcy',
      'immigration',
    ],
  },
  {
    id: 'auto-repair',
    label: 'Auto Repair',
    services: [
      'auto repair',
      'oil change',
      'brake repair',
      'tire service',
      'engine repair',
      'transmission',
      'alignment',
      'car inspection',
      'tune-up',
    ],
  },
  {
    id: 'landscaper',
    label: 'Landscaper',
    services: [
      'landscaping',
      'lawn care',
      'tree trimming',
      'garden design',
      'irrigation',
      'mulching',
      'sod installation',
      'leaf removal',
      'snow removal',
    ],
  },
  {
    id: 'roofer',
    label: 'Roofer',
    services: [
      'roof repair',
      'roof replacement',
      'roof inspection',
      'shingle repair',
      'metal roofing',
      'flat roof',
      'gutter',
      'leak repair',
      'storm damage',
    ],
  },
  {
    id: 'real-estate',
    label: 'Real Estate Agent',
    services: [
      'real estate agent',
      'realtor',
      'homes for sale',
      'buy a home',
      'sell my house',
      'listing agent',
      "buyer's agent",
      'property value',
      'open house',
    ],
  },
  {
    id: 'accountant',
    label: 'Accountant',
    services: [
      'accountant',
      'CPA',
      'tax preparation',
      'bookkeeping',
      'payroll',
      'tax planning',
      'audit',
      'financial advisor',
      'small business accounting',
    ],
  },
  {
    id: 'veterinarian',
    label: 'Veterinarian',
    services: [
      'veterinarian',
      'vet',
      'pet care',
      'dog vet',
      'cat vet',
      'pet vaccination',
      'spay neuter',
      'pet dental',
      'emergency vet',
      'animal hospital',
    ],
  },
  {
    id: 'gym',
    label: 'Gym / Fitness',
    services: [
      'gym',
      'personal trainer',
      'fitness center',
      'yoga',
      'CrossFit',
      'group classes',
      'weight training',
      'membership',
      '24 hour gym',
    ],
  },
  {
    id: 'chiropractor',
    label: 'Chiropractor',
    services: [
      'chiropractor',
      'chiropractic',
      'back pain',
      'spinal adjustment',
      'neck pain',
      'sports injury',
      'posture correction',
      'sciatica',
    ],
  },
  {
    id: 'cleaning-service',
    label: 'Cleaning Service',
    services: [
      'house cleaning',
      'maid service',
      'deep cleaning',
      'move-out cleaning',
      'office cleaning',
      'carpet cleaning',
      'window cleaning',
    ],
  },
  {
    id: 'photographer',
    label: 'Photographer',
    services: [
      'photographer',
      'photography',
      'portrait',
      'wedding photographer',
      'family photos',
      'headshots',
      'event photographer',
      'photo session',
    ],
  },
  {
    id: 'locksmith',
    label: 'Locksmith',
    services: [
      'locksmith',
      'lock change',
      'lock repair',
      'car lockout',
      'house lockout',
      'key duplication',
      'deadbolt installation',
      'smart lock',
      'rekey',
    ],
  },
  {
    id: 'pest-control',
    label: 'Pest Control',
    services: [
      'pest control',
      'exterminator',
      'termite treatment',
      'bed bug removal',
      'rodent control',
      'ant removal',
      'mosquito treatment',
      'wildlife removal',
    ],
  },
  {
    id: 'tow-truck',
    label: 'Tow Truck / Roadside',
    services: [
      'tow truck',
      'towing service',
      'roadside assistance',
      'flatbed tow',
      'jump start',
      'tire change',
      'fuel delivery',
      'accident recovery',
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance Agent',
    services: [
      'insurance agent',
      'auto insurance',
      'home insurance',
      'life insurance',
      'health insurance',
      'business insurance',
      'insurance quote',
      'insurance broker',
    ],
  },
  {
    id: 'moving',
    label: 'Moving Company',
    services: [
      'moving company',
      'movers',
      'local movers',
      'long distance movers',
      'packing service',
      'storage',
      'furniture moving',
      'office moving',
    ],
  },
  {
    id: 'custom',
    label: 'Custom (Enter Your Own)',
    services: [],
  },
]

export const US_STATES = [
  { abbr: 'AL', name: 'Alabama' },
  { abbr: 'AK', name: 'Alaska' },
  { abbr: 'AZ', name: 'Arizona' },
  { abbr: 'AR', name: 'Arkansas' },
  { abbr: 'CA', name: 'California' },
  { abbr: 'CO', name: 'Colorado' },
  { abbr: 'CT', name: 'Connecticut' },
  { abbr: 'DE', name: 'Delaware' },
  { abbr: 'FL', name: 'Florida' },
  { abbr: 'GA', name: 'Georgia' },
  { abbr: 'HI', name: 'Hawaii' },
  { abbr: 'ID', name: 'Idaho' },
  { abbr: 'IL', name: 'Illinois' },
  { abbr: 'IN', name: 'Indiana' },
  { abbr: 'IA', name: 'Iowa' },
  { abbr: 'KS', name: 'Kansas' },
  { abbr: 'KY', name: 'Kentucky' },
  { abbr: 'LA', name: 'Louisiana' },
  { abbr: 'ME', name: 'Maine' },
  { abbr: 'MD', name: 'Maryland' },
  { abbr: 'MA', name: 'Massachusetts' },
  { abbr: 'MI', name: 'Michigan' },
  { abbr: 'MN', name: 'Minnesota' },
  { abbr: 'MS', name: 'Mississippi' },
  { abbr: 'MO', name: 'Missouri' },
  { abbr: 'MT', name: 'Montana' },
  { abbr: 'NE', name: 'Nebraska' },
  { abbr: 'NV', name: 'Nevada' },
  { abbr: 'NH', name: 'New Hampshire' },
  { abbr: 'NJ', name: 'New Jersey' },
  { abbr: 'NM', name: 'New Mexico' },
  { abbr: 'NY', name: 'New York' },
  { abbr: 'NC', name: 'North Carolina' },
  { abbr: 'ND', name: 'North Dakota' },
  { abbr: 'OH', name: 'Ohio' },
  { abbr: 'OK', name: 'Oklahoma' },
  { abbr: 'OR', name: 'Oregon' },
  { abbr: 'PA', name: 'Pennsylvania' },
  { abbr: 'RI', name: 'Rhode Island' },
  { abbr: 'SC', name: 'South Carolina' },
  { abbr: 'SD', name: 'South Dakota' },
  { abbr: 'TN', name: 'Tennessee' },
  { abbr: 'TX', name: 'Texas' },
  { abbr: 'UT', name: 'Utah' },
  { abbr: 'VT', name: 'Vermont' },
  { abbr: 'VA', name: 'Virginia' },
  { abbr: 'WA', name: 'Washington' },
  { abbr: 'WV', name: 'West Virginia' },
  { abbr: 'WI', name: 'Wisconsin' },
  { abbr: 'WY', name: 'Wyoming' },
  { abbr: 'DC', name: 'District of Columbia' },
]
